<?php 
//根据 Annotation 自动生成的路由规则
Route::get('/login','home/Login/index')->name('login_panel');
Route::post('/login','home/Login/logIn')->name('login');
Route::rule('/login/out','home/Login/logOut')->name('logout');
Route::get('/login/code','home/Login/loginCode')->name('login_code');
Route::get('/console/article/edit/[:id]','manager/Article/edit')->name('_articleEdit');
Route::post('/console/article/save','manager/Article/save')->name('_article_save');
Route::post('/console/article/update','manager/Article/update')->name('_article_update');
Route::get('/console/article/delete/:id','manager/Article/delete')->name('_article_delete');
Route::get('/console/article/list','manager/Article/list')->name('_article');
Route::get('/console/category/[:parent]','manager/Category/index')->name('_category');;
Route::post('/console/category/save','manager/Category/save')->name('_category_save');
Route::get('/console/category/edit/:parent/:id','manager/Category/edit')->name('_categoryEdit');
Route::post('/console/category/update','manager/Category/update')->name('_category_update');
Route::post('/console/category/delete/:id','manager/Category/delete')->name('_category_delete');
Route::get('/console','manager/Console/index')->name('console_panel');
Route::get('/console/website','manager/Console/webSite')->name('console_website');
Route::post('/console/website/save','manager/Console/websiteSaveAll')->name('console_website_save');
Route::post('/console/website/update','manager/Console/websiteUpdate')->name('console_website_update');
Route::post('/console/website/create','manager/Console/websiteCreate')->name('console_website_create');
Route::post('/console/website/find','manager/Console/websiteFind')->name('console_website_find');
Route::post('/console/website/delete','manager/Console/websiteDelete')->name('console_website_delete');
Route::post('/console/product/save','manager/Product/save')->name('_product_save');
Route::get('/console/product/[:id]','manager/Product/edit')->name('_productEdit');
Route::get('/console/product/listimg','manager/Product/listImg')->name('_productListImg');
Route::get('/console/product/listtxt','manager/Product/listTxt')->name('_productListTxt');